spring:
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: dffdc9224a360a9d9d908ca4942cff8d
            scope: openid
            redirect-uri: http://localhost:8080/api/cccc
            client-authentication-method: post
            authorization-grant-type: authorization_code
            client-name: kakao
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

  datasource:
    url: jdbc:h2:tcp://localhost/~/kakao;
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        #      show_sql: true
        format_sql: true

logging.level:
  org.hibernate.SQL: debug
  org.hibernate.type: trace


